name: tools
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip:
      - python-dotenv
      - slack_sdk
      - telethon
      - google-api-python-client
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-genai
      - requests
      - feedparser
      - playwright
      - eth-account
      - pyobjc-framework-CoreWLAN
